name: Release Package

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          pnpm run build
          pnpm version $VERSION --no-git-tag-version
          pnpm publish --no-git-checks
